bebraven/platform

- Gemfile
- Gemfile.lock
Task: https://app.asana.com/0/1136372351092870/1142999165564244
It only needs the `SENTRY_DSN` env variable set in Heroku. No other config/code changes.
> Add sentry-raven gem

- Dockerfile
- Gemfile
- Gemfile.lock
- config/environments/development.rb
**Ticket(s)**:
https://app.asana.com/0/1133543009734854/1146936250326599
**Description**:
Breaking out development pieces so it can be merged in. This PR sets up platform to have the RubyCAS Core Server gem and enable communicating with the other boxes in the Braven Dev Network via the `platformweb`.
I also have a PR open on the nginx repo to add the route to the current set up.
https://github.com/beyond-z/nginx-dev/pull/1
**Summary**
- Adds Git to Platform dockerfile
- This is necessary for bundle to install the RubyCAS Core gem
from GitHub
- Adds RubyCAS Core Gem
- Whitelists `platformweb` so other containers can communicate
- This is necessary so that other containers to communicate
with the platform box using platformweb:3020
> Adds RubyCAS Core Gem and Setup for External Communication

- app/controllers/cas_controller.rb
- app/views/cas/_login_form.erb
- config/application.rb
- config/environments/development.rb
- config/environments/test.rb
- config/initializers/rubycas_server_core.rb
- config/rubycas.yml
- db/migrate/20191030035633_initial_rubycas_tables.rb
- db/schema.rb
- lib/beyondz.rb
- spec/capybara_helper.rb
- spec/routing/cas/login_spec.rb
**Ticket(s)**:
https://app.asana.com/0/1133543009734854/1150084536382593/f
**Description**:
This is the first round of tests and refactors to the login route. Now that I have been exposed to Rails and done some reading, I understand what needs to be done. This adds environment application configs, adds missing db columns for RubyCAS Core ActiveRecord gem, cleans up Double Render errors, removes invalid code, and some styling changes. 
**Summary**:
- Adds environment based configs for RubyCAS YML
- Updates migration schema
- Refactors some logic from the original brought over code
- Brings over BeyondZ authenticator since we will be using the system for a bit
- Removes code that is not longer valid in the transfer Sinatra to Rails
- Adds tests for `/login`
> First Round Tests and Refactors for CAS Login

- Gemfile
- config/initializers/honeycomb.rb
- config/secrets.yml
**Ticket(s)**:
https://app.asana.com/0/1133543009734854/1153847903754889/f
**Summary**:
- Adds `require=false` for Gems that are not needed to run the application
- Wraps initialization in check to see if gem is present
- Updates  `HONEYCOMB_API_KEY` to `HONEYCOMB_WRITE_KEY`
- This is so Honeycomb Drain can be used in the future
> Updates to Honeycomb Installation 

- .env.example
- .gitignore
- README.md
- config/environments/test.rb
- config/rubycas.yml
- Make running the specs silent on success instead of printing out a bajillion debug logs.
- Update .env.example to reflect how it should be configured to make the SSO specs pass.
Note: the Selenium driven smoke_spec.rb tests still fail for me. See the selenium_specs branch for more details of my investigation and attempt to fix, but I'm deprioritizing that for now. Also note that the SSO specs don't actually use Selenium b/c they don't need a javascript driver.
> Cleanup up SSO related specs

- Dockerfile
- Gemfile
- Gemfile.lock
- docker-compose.yml
See: https://app.asana.com/0/1156506513832825/1158558207611705
We were running guard with force polling on because using the filesystem
event notificaiton stuff wasn't working. It was pinning the CPU at 100%+
This commit adds libnotify to the Docker container, adds the gem to use it,
and then runs gaurd without forced polling.
**IMPORTANT NOTE:** there are issues with certain editors, like vim, when you
edit from the host machine. For vim, you have to add this setting to your
.vimrc file:
`set backupcopy=yes`
See the following for more details
- https://github.com/guard/listen/issues/434
- https://github.com/guard/listen/issues/420
TESTING:
- Rebuilt the container and edited an .erb file from vim on the host Mac machine
with `backupcopy=yes` turned on. The change was live reloaded.
- …
> Fix high CPU usage on a Mac when running Docker container.

- Gemfile
- Gemfile.lock
- lib/tasks/heroku.rb
This is intended to be used from the Scheduler add-on
(or some other add-on) to restart the dyno in the middle of
the night daily so that we're not at the whims of the dyno
manager cycling it.
TESTING:
- After creating an oauth token using
heroku authorizations:create -d "Platform Admin API token" -s write
I ran:
HEROKU_OAUTH_TOKEN=my-token HEROKU_APP_NAME=my-app bundle exec rake heroku:app:restart_dyno[web]
and verified that the dyno restarted
> Add rake task to restart dynos.

- app.json
- db/dummies.rb
The app.json had everything in the "test" environment, so the
postdeploy script wasn't running. Move the review apps related
postdeploy to the "review" environment and cleanup the buildpack
that applies to all environments.
TESTING:
- F.It, we'll do it live!
(it's the only option)
> Attempt to fix review apps database population.

- app.json
Was getting the following error for CI when deploying. Also, the
ruby buildpack didn't show up in the log.
bash: yarn: command not found
-----> test-setup command `yarn install` failed with exit status 127
> Fixes to app.json -- top level buildpacks didn't seem to work.

- app/controllers/access_tokens_controller.rb
- app/controllers/application_controller.rb
- app/controllers/cas_controller.rb
- app/controllers/course_contents_controller.rb
- app/controllers/industries_controller.rb
- app/controllers/interests_controller.rb
- app/controllers/locations_controller.rb
- app/controllers/majors_controller.rb
- app/controllers/postal_codes_controller.rb
- app/controllers/programs_controller.rb
- app/controllers/roles_controller.rb
- app/controllers/users_controller.rb
- lib/dry_crud.rb
This allows us to create new controllers that inherit from ApplicationController and they auto-magically have the instance variables set that `index`, `show`, and `edit` CRUD methods rely on. I'll be adding more functionality to this for nested resources [over here](https://github.com/bebraven/platform/pull/85#discussion_r376598338) which sparked this PR.
Note: this is by no means high on the priority list of things to do, but it was fun to tinker with and getting some of this stuff setup early one just means less and less code to maintain in multiple spots, so I think it's worth it on both fronts.
TESTING
- all specs pass
- clicked around the various routes to make sure that show, edit, and index routes don't throw exceptions
NOTE:
- I borrowed heavily from for implementation …
> DRY-up our controllers a bit with some meta-programming

- docker-compose/scripts/dbconnect.sh
- docker-compose/scripts/dbrefresh.sh
When I wanted to blow away my dev db my natural inclination was to run `docker-compose exec platformweb rake db:drop db:create` but that doesn't work b/c there are active DB connections. Adding a script (like all our other repos have) to blow away and refresh the dev db.
- adding a ./docker-compose/scripts/dbrefresh.sh to blow away your dev db
entirely and make it fresh
- running the alias `devdb` (or the full script ./docker-compose/scripts/dbconnect.sh)
now connects to the actual database instead of just the db server.
Note: for now db:dummies is how we're seeding a dev db, but we'll likely change that
to somehow load a dev version of staging/prod at some point
TESTING: 
- ran the script. new db
> Make working with the dev database easier.

- app/controllers/course_contents_controller.rb
- app/javascript/components/ContentEditor.js
An ugly, but quick workaround for "modal" inputs in the editor UI.
When you click on the buttons in the right sidebar in the editor, some of them need a way to input different options before inserting a component. E.g. we use this to set the height/width of tables, set the URL to use for iframes/videos/images, etc.
Example workflow:
1. Click the "IFrame" button to insert an iframe
2. You get a popup asking for a URL
3. The popup returns the URL you enter to the JS and stores it in a variable
4. We pass the URL variable into the 'insertIFrame' command, so it knows what URL to use
5. A frame with your custom URL is inserted into the editor
I tried using some actual modal prompt stuff, but I kept hitting dead ends and decided it's more complicated than we have time for. We should get a UX / …
> Use window.prompt for 'modal' input

- README.md
- app/assets/stylesheets/course_contents.scss
- app/assets/stylesheets/style.css
- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/ckeditor/customelementattributepreservation.js
- app/javascript/ckeditor/insertslidercommand.js
- app/javascript/ckeditor/inserttextareacommand.js
- app/javascript/ckeditor/inserttextinputcommand.js
- app/javascript/ckeditor/sectionediting.js
- app/javascript/components/ContentEditor.js
- spec/feature/course_contents/smoke_spec.rb
Summary: Add a toolbar to the right sidebar that only shows up if you have certain elements selected. E.g. when you click on a textarea, it shows a toolbar that lets you change the textarea's placeholder attribute.
Task: https://app.asana.com/0/1142638035116665/1155859225081719/f
We didn't design anything for this, so it's not pretty. Here's what this looks like:
This PR also includes some other, smaller right-sidebar tasks: 
✓ Editor JS: Implement UI for sliders (right sidebar)
✓ Editor JS/CK: Allow setting placeholder text for textareas/inputs (right sidebar)
✓ Editor JS: Remove tabs from right sidebar
✓ Design/Editor JS: organize buttons on right sidebar
> Add context-sensitive right toolbar

- spec/controllers/cas/login_spec.rb
- spec/controllers/cas/logout_spec.rb
- spec/controllers/cas/proxy_validate_spec.rb
- spec/controllers/cas/service_validate_spec.rb
- spec/controllers/cas/validate_spec.rb
- spec/feature/course_contents/smoke_spec.rb
Reverts bebraven/platform#119
The `Test run config vars` under Heroku CI settings needed to be updated to change `SSO_URL` from `http://stagingplatform.bebraven.org/cas/` to `https://stagingplatform.bebraven.org/cas/`.
For good measure, I added `FORCE_SSL=true` since that's the mode we run staging and prod in.
> Revert "marks some failing tests as pending"

- app/javascript/ckeditor/contentcommonediting.js
Purpose: We need `<h6 class="bz-graded-question"></h6>` in question bodies to show the mastery question "icon".
Task: https://app.asana.com/0/0/1166022624267526/f
In action:
> Allow classes on h6

- app/javascript/ckeditor/contentcommonediting.js
Purpose: We need the "dont-mix" class on the fieldset element for checklists/radios/matching games where we don't want the JS to shuffle the options.
Task: https://app.asana.com/0/0/1166022624267523/f
> Allow classes on fieldsets

- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/ckeditor/tablecontentediting.js
Task: https://app.asana.com/0/0/1165367656314881/f
Small change, but we use this in module 1.
Before: 
After:
> Allow h6 in table cells

- app/javascript/ckeditor/checklistquestionediting.js
- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/ckeditor/radioquestionediting.js
- app/javascript/ckeditor/tablecontentediting.js
Extends the work from #121 to cover all other input types. (Sliders, textareas, text inputs, file uploads, dropdowns.)
> Allow all known "data-bz-*" attributes on all remaining input types

- app/javascript/ckeditor/utils.js
- app/javascript/components/ContentEditor.js
See code comments for more details. Also fixes a hardcoded name in a utility function 🤦‍♀.
Test steps:
* Load onboard to braven in the editor.
* Scroll to the bottom and find the matrix under "Big Rock 2".
* Click the table handle
* Press delete
* If the entire editor disappears, you've repro'd the bug. If not, the bug is fixed!
Task: https://app.asana.com/0/1142638035116665/1166022624267529/f
> Fix an annoying editor crash

- app/assets/stylesheets/course_contents.scss
- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/ckeditor/customelementattributepreservation.js
- app/javascript/ckeditor/tablecontentediting.js
- app/javascript/components/ContentEditor.js
This PR:
* Allows `id` attributes (and other custom attributes) on headings
* Adds support for `h5`s in the document root
* Refactors h6 support
* Refactors custom element attribute preservation slightly
* Adds UI support for all heading types
* Fixes UI dropdown styling for heading elements in the editor
Task: https://app.asana.com/0/1142638035116665/1160411399917403/f
> Allow IDs in headings; style heading dropdown

- app/javascript/ckeditor/checklistquestionediting.js
- app/javascript/ckeditor/utils.js
- app/javascript/components/ContentEditor.js
Bugfix: Correctness dropdown wasn't showing up at all, now shows up correctly.
Enhancement: Correctness dropdown now works when the current selection is checkbox/radio inputs, labels, OR parent divs, and updates the data-correctness attribute of the input accordingly.
Screenshot:
Task: https://app.asana.com/0/1142638035116665/1168290061278555/f
NB: Updating the correctness does not currently update the edit view ([bug](https://app.asana.com/0/1142638035116665/1169209719391233/f)). Relying on checkboxDiv / radioDiv means you won't be able to edit correctness in matrices; I think this is acceptable behavior at the moment since we shouldn't be creating new matrices, but it's something we could add in the future if we need to.
> Fix correctness chooser

- app/javascript/ckeditor/contentcommonediting.js
Allows / preserves the "id" attribute in answer titles. (Not much to review here, just an informational PR.)
Task: https://app.asana.com/0/1142638035116665/1169229931357123/f
> Fix answer title ID handling

- app/javascript/ckeditor/radioquestionediting.js
Task: https://app.asana.com/0/1142638035116665/1169229931357115/f
(Not much to review here, just informational PR.)
NB: We'll need something at some point that automatically chooses values for radio inputs ([feature](https://app.asana.com/0/0/1169229931357127/f)). In the mean time, new radio values will all default to 'undefined'.
> Add value attribute handling to radio inputs

- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/ckeditor/insertcontentblockcommand.js
- app/javascript/ckeditor/inserttablecontentcommand.js
- app/javascript/components/ContentEditor.js
Allow users to insert new text content blocks, and fix some minor issues in other buttons for consistency. 
Again, not much to review here. The new file is just a modified copy of the existing commands, they're all pretty much the same.
The one thing to note is that I tried to make the `class` attribute a parameter, but it's not currently working as expected - it just creates a `<div class="module-block">` regardless of what classes you pass in. I'm not sure why, but it's not a blocker at the moment so I'd like to get this in anyway.
Task: https://app.asana.com/0/1142638035116665/1169209719391251/f
> Add an insert-text-block button

- app/javascript/ckeditor/sliderquestionediting.js
Task: https://app.asana.com/0/1142638035116665/1169263114925105/f
context: this element is where we show current-value for sliders. some sliders represent a percent, so they have a `%` symbol in them so that the value shows up as e.g. "50%" instead of "50". this allows us to put %s inside the div.
> Allow text in displayValueDiv

- app/javascript/ckeditor/checklistquestionediting.js
- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/ckeditor/customelementattributepreservation.js
- app/javascript/components/ContentEditor.js
Task: https://app.asana.com/0/1142638035116665/1169382763057601/f
Summary: allows the custom "div" element inside `checkboxDiv` and `questionFieldset`, because those are the two places we currently use `div class="share-release"`.
example: 
context / things to note: This "custom div" code is super fragile, and our goal should be to eventually phase it out. We can do this by implementing more things (like this share-release div) as fully supported elements, and/or by removing them from the modules entirely (this should be preferred).
> Handle share-release divs/checkboxes

- app/javascript/components/ContentEditor.js
- app/views/course_contents/_form.html.erb
- app/views/course_contents/edit.html.erb
- app/views/course_contents/new.html.erb
Summary: Save button was hidden behind other links and in some cases the editor component itself, making it hard to click. There's now a save button at the top of the screen, next to publish.
Task: https://app.asana.com/0/1142638035116665/1170308508489041/f
Before:
After:
> Move save button, remove unused links

- app/javascript/components/ContentEditor.js
There's no task for this.
Summary: Adds more `CourseContent` fields to the editor UI, so they're easier to set/update.
Screenshot:
Context: The way i've been doing this is going through heroku web interface -> staging platform console -> find the `CourseContent` with the right id -> set each of the 3 fields correctly -> save the record -> back to editor -> publish. Now I can just fill out the fields in the editor -> save -> publish. This'll save me a lot of time.
> Add advanced page options

- app/controllers/course_contents_controller.rb
- app/views/course_contents/edit.html.erb
- spec/controllers/course_contents_controller_spec.rb
There's no task for this.
Summary: Instead of going to a messy "show" page after saving, just show the editor page again. 
Before:
After:
> On save, show the edit page

- app/javascript/ckeditor/contentcommonediting.js
Task: https://app.asana.com/0/1142638035116665/1170711919744948/f
Summary: Normalize where input-type elements are allowed - all of them should be allowed inside fieldsets.
This is a blocker for module 3.
> Allow all inputs inside fieldset

- app/javascript/ckeditor/portalimageediting.js
- app/javascript/components/ContentEditor.js
Task: https://app.asana.com/0/1142638035116665/1170693002395763/f
Summary: Prepend `https://portal.bebraven.org` to image `src` attributes that begin with `/`, only in the editing view.
Context: We have a lot of images in modules that have `src='/blah'`, and they don't render in the editor because it's hosted on a different domain than canvas. This PR makes it easier to edit existing modules. By using this custom converter on the editingDowncast chain ONLY, we avoid modifying any of the actual content, so it works transparently when publishing to portal. 
Before:
After:
> Render portal images correctly in the editor

- app/javascript/components/ContentEditor.js
Task: https://app.asana.com/0/1170776727341290/1159217855939649
Test: 
- Copy-paste code from here: https://stagingplatform.bebraven.org/course_contents/1/edit
- Change text in "Design" tab, no lag
- Switch to "Code" tab, check that change is there
- Edit in "Code" tab, switch back, make sure changes are in "Design" tab
Details:
- When in "Code" tab, track the data in `this.state.editorData` because there's not logically a WYSIWYG `editor` in this view.
- When in "Design" tab, initialize with data from `this.state.editorData`, but then let `editor` track the content and don't touch `this.state`.
- This means we don't have to call `this.setState()` for the content and cause the entire editor to re-render every time we type, which was causing the lag. 
- Only when switching to "Code," …
> Fix editor performance

- app/javascript/ckeditor/customelementattributepreservation.js
Task: https://app.asana.com/0/1170776727341290/1171656365267757/f
This is a module 7 blocker, required for interactive rubric JS.
(Note: branch based on editor-css-overrides, remember to merge into staging after #156)
> Preserve data-bz-retained on links

- app/javascript/ckeditor/videocontentediting.js
Task: https://app.asana.com/0/1142638035116665/1169461014498427/f
Setting the elements as limits prevents the cursor from escaping them, which means select-all inside one of them only selects all the contents of that element.
> Fix editor video selection

- app/javascript/ckeditor/checklistquestionediting.js
- app/javascript/ckeditor/insertcheckboxcommand.js
- app/javascript/ckeditor/insertradiocommand.js
- app/javascript/ckeditor/radioquestionediting.js
Task: https://app.asana.com/0/1170776727341290/1170308508489046/f
This is another one where I don't fully understand why it works this way.
As a side-effect of this PR, the `insertCheckbox` / `insertRadio` commands are much more robust and less hardcoded-y.
To test: 
1. Insert a section
2. insert a checkbox (or radio) question
3. select the option, outside the checkbox label or inline feedback, so the blue outline shows up.
4. hit enter; note that a new option is inserted after the current option.
> Allow inserting options with the entire option selected, instead of just inside the label

- app/assets/stylesheets/course_contents.scss
- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/components/ContentEditor.js
Task: https://app.asana.com/0/1170776727341290/1172440855762345/f
3 things included in this PR:
* New context-sensitive right sidebar block for videos and iframes
* New attributeToAttribute converter so `src` live-updates in the editing view
* CSS to make the border thicker on iframes, so they're easier to select.
We can't use the CKE selection handle on iframes unfortunately; see https://github.com/ckeditor/ckeditor5/issues/6650 for more details. This CSS change is my workaround for that. If anyone has better CSS ideas, let me know!
> Allow designers to edit video/iframe URLs

- app/assets/stylesheets/course_contents.scss
- app/views/course_contents/show.html.erb
- spec/views/course_contents/show.html.erb_spec.rb
Task: none
Summary: Renders HTML in the `show` page, to make it easier for me to download the full HTML without having to unescape a bunch of characters or something. I did this now so I can get the HTML from the modules on prod and clean up the duplicate-tooltip-span mess.
Screenshot:
> Render HTML on the show page

- app/javascript/components/ContentEditor.js
- app/javascript/components/ContentPartPreview.js
**Task**: https://app.asana.com/0/1170776727341290/1169251338691091
**Test**
- Insert section, radio question, click into label
- Try clicking greyed out buttons in `Insert Component`
- Verify that nothing happens, e.g. prompt for rows/columns when you click `Insert Table` and that focus stays in the label area
**Details**
- If the button is disabled, don't run the `onClick` event handler. 
- But we don't want to loose focus on the element the designer was editing previously, so we need to still execute the focus event. 
- The `onClickDisabled()` handler has to be a lambda so the code isn't evaluated when the component is instantiated and only run when clicked. E.g., I said `onClickDisabled=this.editor.editing.view.focus}` would be equivalent, but that's not true because it tries to …
> Don't execute click handler when disabled buttons at clicked

- app/javascript/ckeditor/tooltipediting.js
This addresses both the double-tooltip upcast issue, and the tooltip-within-list issue.
Task: https://app.asana.com/0/1170776727341290/1161453930156673/f
Task: https://app.asana.com/0/1142638035116665/1169229931357117/f
Test with:
```html
<ol>
<li><span class="has-tooltip" title="test-title">Text</span></li>
</ol>
```
Toggle back and forth between Design/Code a few times, and note it doesn't create duplicate spans, nor does it crash the editor.
Reference: https://github.com/ckeditor/ckeditor5/issues/4529
> Fix tooltip converter

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/course_contents.scss
- app/views/course_contents/_form.html.erb
I'm working on new account creation forms and these hacks where
conflicting with my stuff. I'll leave it up for a future "for real"
fix, but for now I'm just making them content editor specific.
> Moving CSS content editor hacks to only impact that form.

- app/javascript/components/ContentEditor.js
Two changes:
1. Add a textInput button (the command already existed).
2. Set the default placeholder for both textInput/textArea to the empty string `''`, to fix the following 2 issues:
a. When inserting a textarea/input, the default placeholder shows up as the literal string `undefined`.
b. When attempting to edit the default placeholder, the editor crashes, and undo breaks.
Button Task: https://app.asana.com/0/1170776727341290/1173719663284395/f
Placeholder Task: https://app.asana.com/0/1170776727341290/1173719663284397/f
> Add textInput button, fix textArea/Input placeholders

- db/dummies.rb
The admin account for Booster is different from the existing portal/staging ones. It's `booster.admin@bebraven.org` instead of `admin@{beyondz,bebraven}.org`. 
I ran into this because my local `canvasweb` uses Booster data fetched with `dbrefreshbooster.sh`. When I login to `canvasweb` with `admin@`, I get an error because that email doesn't exist in the Booster's user emails. 
Adding the Booster admin email `db/dummies.rb`, so after you `dbrefresh` , you can login.
> Add admin for Booster to dummies.rb

- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/ckeditor/insertdonebuttoncommand.js
- app/javascript/ckeditor/utils.js
- app/javascript/components/ContentEditor.js
Task: https://app.asana.com/0/1170776727341290/1172766526299157/f
Summary: Allow designers to add "Done" buttons to content blocks, but nowhere else.
Testing procedure:
* Load empty editor, note that "Done Button" button is disabled
* Insert section, note that "Done Button" button is disabled
* Insert question (any type), click around inside editor, note that "Done Button" button is always disabled
* Delete question, so you have an empty section again
* Insert "Text" content block (not "Text Area" or "Text Area Question")
* Note that "Done Button" button is enabled.
* Click around inside the text content-block, note that "Done Button" button remains enabled.
* Click on module-block so the border turns blue. 
* Click "Done Button" button
* Verify button is inserted at bottom of block.
* …
> Allow adding done buttons to content blocks

- app/javascript/ckeditor/checklistquestionediting.js
- app/javascript/ckeditor/insertchecklistothercommand.js
- app/javascript/components/ContentEditor.js
Task: https://app.asana.com/0/1170776727341290/1172646780976523/f
Summary: Add an `"Other" Checkbox with Text Area` button, to let designers add "Other:" checkboxes to checklist questions.
Testing procedure:
1. Note the "Other" button is disabled
1. Insert section, insert checklist question
2. Click on/in the first checklist option; note the "Other" button changes to enabled
3. Click the "Other" button; verify a new option with a textarea is added after the currently selected option.
Other notes:
* "Other" options have no inline-feedback, by design.
* Both the checkbox `<input>` and the `<textarea>` will have the `data-bz-optional-magic-field="true"` attribute. This is used by the module JS as part of autograding.
* The "Other" checkbox will have `data-correctness` automatically set to …
> Add checklist-other button

- app/assets/stylesheets/course_contents.scss
No task, this was just annoying me.
Now the editor can get as tall as the right sidebar, if you have a lot of content. Makes it easier to click buttons.
> Adjust editor max-height for (right-sidebar) inflation

- app/controllers/salesforce_controller.rb
- app/models/user.rb
- app/views/salesforce/_form.html.erb
- lib/canvas_api.rb
- lib/salesforce_api.rb
- lib/sync_to_lms.rb
- lib/tasks/salesforce.rake
- spec/factories/salesforce_participant.rb
- spec/lib/salesforce_api_spec.rb
- spec/lib/sync_to_lms_spec.rb
- spec/models/user_spec.rb
https://app.asana.com/0/1170770467635599/1173648174910505
We have two separate servers running the Portal, one for normal Braven and one
for Braven Booster. There may be conflicts with the course_id. Also, for Booster
we're going to have a "Holding" Program and then split folks out into Program's
specific to the run of the program they're taking. Also, folks may sign-up last
minute and we need to provision their account in Canvas. Lastly, Booster folks will not
be mapped to a Cohort. They will have a scheduled day/time and we need to add them
into Canvas in corresponding sections.
This commit aims to solve all that.
In addition to making Sync To LMS run off the Salesforce Program, it also changes
the account creation / sign_up to create their Canvas account on the fly at the time they …
> Refactor Sync To LMS and account creation to work with Salesforce Programs

- app/javascript/components/ContentEditor.js
**Task**: https://app.asana.com/0/1170776727341290/1159217855939646
**Test**
- Here's a `.mov` screen recording of the fix, but GitHub only allows me upload it as a `.zip`: [Screen Recording 2020-05-06 at 3.49.04 PM.mov.zip](https://github.com/bebraven/platform/files/4589840/Screen.Recording.2020-05-06.at.3.49.04.PM.mov.zip)
- Add new section, new checklist question
- Make three answers using "enter" to add them
- Change correctness to "Correct", "Incorrect", "Maybe"
- Click between the answers and observe the selector on the right updates
**Details**
- I think this is one of the issues covered by the Asana task and I think it's going to be easier to fix than we initially thought.
> Update correctness selector when you click on an answer

- app/assets/stylesheets/course_contents.scss
- app/javascript/ckeditor/blockquotecontentediting.js
**Task**: This facilitates designers changing icons. This PR allows us to differentiate the block-quote styling class from icon classes. 
**Test**
- Add new section, insert quote, check that renders correctly:
(The left padding is wrong from the `canvas-lms-js-css` code. I'll put up a PR for that.)
- Also check the HTML:
- Publish to check Portal side:
- You can also paste this into the `Code` tab of the editor: https://pastebin.com/sZT93ZUH
(there are a bunch of other content/question sections because I was worried about impacting that CSS). 
*Details*
- This is part of allowing designers to change icons. 
- We need to differentiate between `module-block-{quote, textarea}` classes, which represent different types of content blocks (and affect styling of the section) `module-block-{video, …
> Rename module-block-quote => block-quote-bg

- app/assets/stylesheets/course_contents.scss
- app/javascript/ckeditor/blockquotecontentediting.js
- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/ckeditor/insertblockquotecontentcommand.js
- app/javascript/ckeditor/insertcontentblockcommand.js
- app/javascript/ckeditor/insertmatchingquestioncommand.js
- app/javascript/ckeditor/insertmatrixquestioncommand.js
- app/javascript/ckeditor/insertsliderquestioncommand.js
- app/javascript/ckeditor/inserttablecontentcommand.js
- app/javascript/ckeditor/inserttextareaquestioncommand.js
- app/javascript/ckeditor/insertvideocontentcommand.js
- app/javascript/ckeditor/matchingquestionediting.js
- app/javascript/ckeditor/matrixquestionediting.js
- app/javascript/ckeditor/moduleblockediting.js
- app/javascript/ckeditor/sliderquestionediting.js
- app/javascript/ckeditor/tablecontentediting.js
- app/javascript/ckeditor/textareaquestionediting.js
- app/javascript/ckeditor/videocontentediting.js
- app/javascript/components/ContentEditor.js
**Task**: https://app.asana.com/0/1170776727341290/1172273996801759
**Test**
**Without CSS changes, looking at `data-icon` attribute**
- Add `?debug` and use CKEditor inspector to check that `data-icon` gets set in Model and View
- Toggle between Design/Code tabs to make sure the change sticks in HTML
- Check upcast by adding new section, new checklist question, toggle to HTML, no `data-icon`, toggle back to Design to trigger upcast converter, toggle back to HTML, verify there's now a `data-icon=module-block-question`. (Sorry, this one was hard to describe. I can demo this if that makes it clearer!)
**With CSS changes**
- Manually change `new_bravenui.css` in Chrome inspector to: https://github.com/beyond-z/canvas-lms-js-css/pull/296
- Check that icon updates now when we use the selector …
> Implement icons as data attribute

- Dockerfile
Without this, `docker-compose build` fails: 
```
error /usr/src/app/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /usr/src/app/node_modules/node-sass
Output:
Building: /usr/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/src/app/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using …
```
> HOTFIX: Add python2 as a dependency so the container can build again

- app/javascript/ckeditor/insertchecklistothercommand.js
This is a detail I missed in #187. By default, the module JS shuffles the order of options in a checklist. To stop it, we add the `dont-mix` class on the `fieldset` surrounding the `checkboxDiv`s. Since "Other" options always have to be at the end, we always want `dont-mix` on checklists with "Other" options.
Task: https://app.asana.com/0/1170776727341290/1172646780976523/f
> Add dont-mix to checklists with 'other' options

- Dockerfile
- Gemfile
- README.md
- docker-compose/scripts/docker_compose_run.sh
We never use the packages we install at build time, because of the `node-modules` volume that gets mounted over top of them. Move yarn to the start script instead.
Results: 
* Container build is much faster ✅ 
* Container is smaller ✅ 
* Startup is 7s slower (on subsequent runs) ❌ 
* Startup is more reliable (no more yarn check failures! auto-installs new JS packages on container restart!) ✅
> Move yarn install from build to startup

- app/assets/stylesheets/course_contents.scss
- app/javascript/ckeditor/insertsectioncommand.js
- app/javascript/ckeditor/sectionediting.js
Problem: The module JS expects sections to only have one module-block and nothing else. The booster content has many things inside sections. This causes the done-button JS to break and show everything inside the section.
Proposal: Highlight things that are invalid inside a section, to encourage the designer to fix them. I didn't enforce this from CKE because it doesn't seem possible from [addChildCheck](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html#function-addChildCheck), and I don't know another good place to put it.
Proposal part 2 (2020-05-07): Fix remaining pain points, without invalidating/mangling existing incorrect content. Additions as follows - 
* Disallow typing within sections. (Still allows ctrl-z/{ctrl-shift-z,ctrl-y}, …
> Highlight invalid things inside sections, and disallow adding all but a single module-block to sections.

- app/javascript/components/ContentEditor.js
**Task**: N/A, following up on https://github.com/bebraven/platform/pull/192
**Test**
- Screencast: [test2.mov.zip](https://github.com/bebraven/platform/files/4596105/test2.mov.zip)
- New section, add "Text Area", "Text Input", type in different placeholder texts, click between them, see that it changes on the RHS
**Details**
- Going through these one at a time so I actually test them. There a whole bunch in `ContentEditor.js`, but they're straightforward to tackle so far. 
- When we use `defaultValue`, we're telling React to treat the component as "uncontrolled", which really is just "let the DOM handle it, React treat it as opaque." But we never generate a reference for the input, so React has no idea what in the DOM to update. This is the React documentation on it: …
> Fix Text Area and Text Input placeholder updating

- app/assets/stylesheets/course_contents.scss
Tables default to left-aligned text when published to Portal, but are centered when displayed in the editor. This fixes that.
Task: None (noticed while working with Tess a while back)
> Tables default to left-aligned text

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
- docker-compose/scripts/docker_compose_run.sh
In my case, I need to debug some issues in this gem
https://github.com/bebraven/rubycas-server-core so with this change I can
now just go into the container, navigate to the code in `vendor/bundle`
add logs or `binding.pry` statements, restart the container and the changes
will be run.
Note the comment in the README about needing to blow away the vendor-bundle
volume if you muck it up too much and want to get back to a pristine state.
> Add easier way to troubleshoot issues in gems.

- app/views/home/welcome.html.erb
- config/rubycas.yml
- spec/rails_helper.rb
Enable single-signout setting in SSO server.
With enable_single_sign_out set to true, it calls into each app that has authenticated
with this ticket and tells them to logout.
The `enable_single_sign_out` setting was only enabled in the test
configuration. It should be enabled for all environments. I think this was an
oversight. Refactor the whole rubycas.yml settings file so that shared settings
are defined in one place and each env only changes settings specific to it. 
platform logout
1. Login to platform.
2. Login to portal in a separate tab.
3. Logout of platform.
4. Try to hit a new page in portal, it should redirect to the sign-in page.
portal logout
1. Repeat step 1 & 2 above.
2. Logout of Portal
3. Try to hit a new page in platform, redirects to sign-in page.
> Make SSO logout work properly

- app/javascript/components/ContentEditor.js
task: https://app.asana.com/0/1170776727341290/1174569613518649/f
docs: https://ckeditor.com/docs/ckeditor5/latest/features/image.html#using-pixels-instead-of-percentage-width
before (`style="width:31.8%;"`):
after (`style="100px;"`):
> Use px instead of % for image resize

- app/controllers/cas_controller.rb
- app/controllers/users/confirmations_controller.rb
- Register a new user who has Portal access and when you click the email
confirmation link it logs you into the Portal.
- Note: we currently don't have a way to register an admin user without
Portal access, so we can't test that. When the day comes it'll break
if I got it wrong
> Auto login the user when they confirm their new account.

- app/controllers/application_controller.rb
- app/controllers/cas_controller.rb
- app/controllers/users/passwords_controller.rb
I'd rather have them login directly after changing their password vs
auto logging them in so they can update their password management
software or do whatever they normally do to keep track of passwords.
Note: I tried to use some better approaches to do this but it was taking
way too much time. So I'm just piggybacking off the existing message
notices for the cas login form and sticking with a GET request. Also
fancier query param parsing / manipulation stuff wasn't worth it.
Test Plan
- Click forgot password, enter your email, click the link in the email
and you should see a message saying it was successful on the sign-in form
you're redirected to.
> On forgot password reset success, display a message.

- app/assets/stylesheets/reboot.css
No task. Fixes this annoying error on every page load:
```
platformweb_1      | ActionController::RoutingError (No route matches [GET] "/assets/bootstrap-reboot.css.map"):
platformweb_1      |
platformweb_1      | actionpack (6.0.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
platformweb_1      | web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
platformweb_1      | web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
platformweb_1      | web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
platformweb_1      | web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
platformweb_1      | actionpack (6.0.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
platformweb_1      | railties (6.0.2.2) …
```
> Remove broken map reference

- app/javascript/ckeditor/insertradioquestioncommand.js
- app/javascript/ckeditor/moduleblockediting.js
- app/javascript/ckeditor/radioquestionediting.js
Task: https://app.asana.com/0/1170776727341290/1172643959550099/f
Basically, I have no idea how radio buttons work, so I implemented this totally backwards. This PR fixes that.
I'd appreciate if someone can double-check my logic, bc this is confusing.
Things to know:
* Radio group **MUST** be unique for each question. Every button in the question shares the group.
* Group is tracked for convenience in `module-block[data-radio-group]`, but is actually determined by the radio `input`'s `name` attribute.
* Each radio has an `id` attribute that **MUST** be unique in the document.
* Each radio has a `data-bz-retained` ID that **MAY** match the `name` attribute, and **MUST** be the same for all radio `input`s in a group.
* Each radio has a `value` attribute that **MUST** be unique within each …
> Fix radio questions

- app/models/user.rb
- lib/salesforce_api.rb
- spec/lib/salesforce_api_spec.rb
- spec/models/user_spec.rb
Test plan:
- Sign-up a new Enrolled Participant from Salesforce. See that their
Canvas User ID field gets set on the Contact record
> Store newly created Canvas user's canvas_id in Salesforce.

- app/javascript/ckeditor/insertsliderquestioncommand.js
- app/javascript/components/ContentEditor.js
Task: https://app.asana.com/0/1170776727341290/1176387214965594/f
Task: https://app.asana.com/0/1170776727341290/1173560888333813/f
We don't actually want data-bz-answer on all sliders, that attribute is only used for mastery questions.
> Fix slider answer attributes

- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/ckeditor/insertchecklistquestioncommand.js
- app/javascript/ckeditor/retaineddata.js
**Task**: https://app.asana.com/0/1170776727341290/1170693002395753
**Test**
**Link on `<contentTitle>`**: check with `?debug` in model/view of CKE inspector
**Link on `<questionTitle>`**: check with `?debug` in model/view of CKE inspector
**Link on `<answerTitle>`**: check in `Code` tab:
**Published to `canvasweb`**: click and make sure anchor links work
*question and content titles are linked*
*answer title is linked*
**Details**
- CKE gave us a solution here: https://github.com/ckeditor/ckeditor5/issues/6815
- The individual commits here a mess, but if you look at the `Files changed`, that should look sane. 
- We need to Save twice to get all the conversions to run to assign the `id` and `toc-link-href`, which isn't ideal. 
- The implementation steps are roughly:
-- Expose the counter …
> Add anchor link to <{question, answer, content}Title>

- Dockerfile
No task. We don't ever want the docker build to update the Gemfile.lock, as that defeats the purpose of having a lockfile: builds should be consistent and repeatable.
> Freeze bundle install in Dockerfile

- README.md
`docker-compose down -v` doesn't take arguments, you have to use the docker command
> Fix docker volume remove command

- app/javascript/ckeditor/contentcommonediting.js
- app/javascript/ckeditor/customelementattributepreservation.js
- app/javascript/ckeditor/retaineddata.js
**Task**: https://app.asana.com/0/1170776727341290/1176606860502193
**Test**
Manually type some text, highlight and set heading in drop-down:
Toggle between Design/Code and check with `?debug` in CKE inspector that `id` and `toc-link-href` are being set:
Publish to `canvasweb` and check that table of contents is generated properly:
To test the anchor links, I padded out with some questions & answers to make the browser scroll. I also made sure the `<h5>` from the `<{question, answer, content}Title>`s weren't showing up in the table of contents:
Made sure that merging of attributes works by manually changing code to add `class=jess-test` on a heading: 
Go back to `Design` and make sure it's still in the model:
**Details**
- Need to update `retaineddata`'s `_consumeAttributeEvent()` to look …
> Add id and toc-link-href to h1-5

- app/javascript/ckeditor/contentcommonediting.js
Fixes a bug where title h5s are assigned a possibly non-unique ID, because upcast runs before the RetainedData plugin has enumerated existing IDs. No task.
> Remove default ID from Title element upcasts

- docker-compose/scripts/rebuild.sh
A rebuild should get you in a clean state. The volume may have old gems
and stuff, so go ahead and remove it on rebuild to get back to a pristine condition.
Test Plan:
- run: docker-compose/scripts/rebuild.sh and make sure it builds and you can
still login / use the platform
> Remove the vendor/bundle volume on rebuild.

- app/controllers/cas_controller.rb
- app/models/user.rb
- lib/cas_authenticator.rb
See: https://app.asana.com/0/1170770467635599/1172738433561916
Test Plan:
- Register a new user but don't click the confirmation link. Try to login.
You should get a message about needing to confirm first.
- Confirm the user, then try a bad password. You should get a message about
a bad username or password.
- Then make sure you can login.
> Show error message if user tries to login before confirming account.

- .env.example
- app/assets/stylesheets/accounts.scss
- app/views/cas/login.html.erb
- config/environments/development.rb
- config/rubycas.yml
**Note: when releasing this, make sure and set the BOOSTER_PORTAL_DOMAIN env var**
If folks don't bookmark the booster login link and just google
Braven, they'll likely end up at https://bebraven.org and hit
Log In at the top-right. That will bring them to the normal
Accelerator login. On that server, this commit adds a link to login
to the Booster portal if that's what they were looking for.
See: https://app.asana.com/0/1170770467635599/1173563708676233
- Go to the login page with APPLICATION_HOST set to something with
booster in it and the link shouldn't be there. Change the APPLICATION_HOST
to something without booster in it and the link to login to Booster should
show up on the login page.
> On a non Booster server, add a link to the Booster login.

- lib/canvas_api.rb
- spec/lib/canvas_api_spec.rb
This is dumb, but when we do course copy or content import in the Portal,
it strips out the leading comments. Nested comments inside the div work.
The JS doesn't care where this token is.
See: https://app.asana.com/0/1170770467635599/1178021488868222
- Push content to Portal. Copy the course with the content and make sure in the
copied course the BRAVEN_NEW_HTML token is in the HTML and the new JS and CSS
runs/is applied.
> Fix Course Copy on the Portal side of things.

- Gemfile.lock
Note the ENV vars that need to be set in production for this to work.
Test Plan:
- Invite a Particpant to signup. Signup and sign DocuSign. Then run bundle exec rake sync:docusign_to_salesforce and in addition to the Student Waiver SIgned field being updated in Salesforce, they should be invited to join the Slack channel for their peer group
> Add slack integration to the rake task to sync Student Waivers.

- app/assets/stylesheets/accounts.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- config/locales/en.yml
See: https://app.asana.com/0/1170770467635599/1175130656011747
- Signup with mismatching passwords, with passwords too short, and with
and existing user. Only one error messaage should be shown and if you
keep making errors the signup form should still look the same. just with
the current errror shown
> Nicer error messages when creating an account.

- app/models/user.rb
- lib/sync_to_lms.rb
There was an error if a user has enrolments. This is caused by a check that assumes enrolments will be returned as an object. This PR:
> Add check if enrolments is an array

- app/models/user.rb
- spec/models/user_spec.rb
This ensures that all new users go through canvas setup. There was an issue where returning LCs will no be placed in the right sections. This solves it by:
> Ensure that all new sign creates go through canvas setup

- config/application.rb
The most notable difference in this change is that Rails 6.0 auto-loader
defaults to zeitwerk and that protect_from_forgery was moved to ActionController::Base.
See:
- https://app.asana.com/0/1179330853755533/1167505329038728
- https://app.asana.com/0/1179330853755533/1159485936661651
- bundle exec rspec
- Sign in, sign up, and Content Editor publish still work (main three features that are live so far.
- Rebuild in production mode and make sure the above works.
- If anything else breaks, let's just fix it. We're early enough in this codebase that we should do this now and just deal with any side effects asap.
> Change config defaults from Rails v5.2 to v6.0

- Gemfile
- Gemfile.lock
- README.md
- app/controllers/keypairs_controller.rb
- app/models/keypair.rb
- config/routes.rb
- db/migrate/20200317113750_create_keypairs.rb
- db/schema.rb
- spec/factories/keypair.rb
- spec/models/keypair_spec.rb
Adds an endpoint to expose a public Json Web Key (JWK).
When implementing a JWK authentication flow (e.g. for LTI Extension),
you need to expose a public JWK that the external service will use to encode
payloads. You need to keep the private key and be able to decode those payloads
(e.g. a JWT id_token) using it. This commit adds the endpoint to expose the public JWK
along with the ability to store and decode payloads using the private key.
See:
-  https://www.imsglobal.org/spec/lti/v1p3#json-web-token-0
- Step 3 here: https://canvas.instructure.com/doc/api/file.lti_dev_key_config.html#launch-overview
- In the Rails console run Keypair.create! and make sure that when you go to
https://platformweb/public_jwk that you can see the public JWK for it.
- Encode a payload using that pulic JWK …
> Implement a Public JWK Url endpoint 

- .env.example
- app/controllers/lti_launch_controller.rb
- app/models/lti_launch.rb
- config/routes.rb
- config/secrets.yml
- db/migrate/20200625120447_create_lti_launches.rb
- db/schema.rb
- lib/lti_id_token.rb
- spec/api_helper.rb
- spec/controllers/lti_launch_controller_spec.rb
- spec/factories/lti_launch.rb
- spec/factories/lti_link_launch_request.rb
- spec/models/lti_launch_spec.rb
This implements the flow described here:
https://canvas.instructure.com/doc/api/file.lti_dev_key_config.html#launch-overview
- Configure your Developer Key with the Redirect URI that exactly matches
`https://ENV['APPLICATION_HOST']/lti/launch`
- Do an LTI Launch, e.g. if your LTI has a Link Selection placement,
go to a Module, click the + to add something, select External Tool,
then click on the name of your LTI. It should start the launch flow and
successfully load the Target URI that you configured in the Developer Key
for the Link Selection placement. E.g. https://platformweb/whatever/endpoint/i/implement in the image below
- In future requests, you can access the metadata about the current LTI Launch (e.g. user_id, etc) using: `LtiLaunch.current(session[:session_id])`
- The following …
> Implement the LTI Launch flow.

- .env.example
- lib/lti_id_token.rb
It only crashes rspec if you don't have env vars set up.
Be sure to add honeycomb settings to your `.env`:
```sh
HONEYCOMB_DATASET=development
HONEYCOMB_WRITE_KEY=
```
Get the key from here: https://ui.honeycomb.io/teams/braven
> Add the honeycomb stuff back

- config/initializers/content_security_policy.rb
This PR allows inline styles like `<div style="color: red;">` on platform. This is insecure.
More info: https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#rule-4-css-escape-and-strictly-validate-before-inserting-untrusted-data-into-html-style-property-values
We're allowing this because we have inline styles in module content, and fixing all of those would be a significant amount of work. Moving forward, we should:
1. Not add additional inline styles to any page.
2. Not allow inline styles in the stripped-down assignments-only content editor.
3. Once we move content to Rise 360 and no longer have old modules, remove this rule from the CSP config.
Task: https://app.asana.com/0/1156506513832825/1184172178554017/f
> Allow unsafe inline styles

- Gemfile
- config/initializers/honeycomb.rb
When the Rails.application.secrets.honeycomb_write_key was empty,
the honeycomb gem wasn't even loaded and so calls to Honeycomb.start_span
would fail. This lets you leave it blank in dev and we always want to
load it in prod anyway.
> Make honeycomb not error out if the write key is blank

- app/models/keypair.rb
Had to go deep into the Rails code to figure this out. Basically,
in production this wouldn't be a problem, but in Dev and Test, Rails
dynamically generates the secret_key_base and stores it in
`tmp/development_secret.txt` -- when switching around branches and rebuilding
the container, this probably get blown away or somehow regenerated which causes
all previously stored keypairs to fail to decrypt b/c the key changed. We
already put a dev `SECRET_KEY_BASE` in the `.env.example`, so after truncating
the keypairs table in dev this shouldn't be a problem anymore.
Test Plan
- bundle exec rspec
- Run `Keypair.create!` in the console and hit http://platformweb/public_jwk
Rebuild the container and remove `tmp/development_secret.txt`. The public_jwk
URL should still return the public JWK for the …
> Fix OpenSSL::Cipher::CipherError with the public JWKs.

- Gemfile
- Gemfile.lock
- app/models/lesson_content.rb
- config/application.rb
- config/routes.rb
- lib/lesson_content_publisher.rb
- lib/lti_lesson_contents_proxy.rb
- spec/lib/lesson_content_publisher_spec.rb
- spec/lib/lti_lesson_contents_proxy_spec.rb
- spec/rails_helper.rb
- spec/support/http_streaming_response_patch.rb
Now we can give Canvas a URL to launch on our server for the Rise360
lesson content which is hosted on AWS S3 and our server will proxy the
request/response so that both Canvas and the browser think the files
live on our server which we can more easily control the trusting relationship
we've developed. We need this b/c the content tries to Ajax request xApi statements
to the LRS but since it's cross-origin things go awry. The above task has more 
context on the discussion: https://app.asana.com/0/1174274412967132/1186566037117865/f
Example:
https://platformweb/lesson_contents_proxy/lessons/ytec17h3ckbr92vcf7nklxmat4tc/index.html?actor=%7B%22name%22%3A%22LESSON_CONTENTS_USERNAME_REPLACE%22%2C%20%22mbox%22%3A%5B%22mailto%3ALESSON_CONTENTS_PASSWORD_REPLACE%22%5D%7D&endpoint=https%3A%2F%2Fplat …
> Adds a reverse proxy to the AWS S3 hosted files for the LTI lessons.

- package.json
This is causing the deployment on heroku to fail. It is not reproducible on local since the flow is different.
> Move loader plugins from devDependencies

- app/services/setup_portal_account.rb
- app/services/update_join_users.rb
- lib/join_api.rb
- lib/tasks/maintenance/update_join_users.rake
- spec/lib/join_api_spec.rb
- spec/services/update_join_users_spec.rb
This adds canvas user to canvas user when creating join user on sign up
Join users without canvas user id cause a weird error
> Add canvas user id when creating user at join

- lib/lti_rise360_proxy.rb
- spec/lib/lti_rise360_proxy_spec.rb
Followup to this task: https://app.asana.com/0/1174274412967132/1199668138554725
The fonts are linked in from a Rise360 CSS file which is the Referer.
Since we use the state param in the Referer to authenticate, the fonts
fail to load with a 401. Its fine to serve unauthenticated font files,
so just exclude them.
Load a Rise360 Module and notice the following errors in the browser console:
After this change, the error goes away and those fonts load.
> Exclude font files from being authenticated for Rise360 packages.
