.gitignore, Dockerfile
This PR addresses some of the issues @sadleb raised in PRs #6 and #7. See comments in those PRs for additional context.
=> Fix issues

Dockerfile, Gemfile, Gemfile.lock, Guardfile, app/javascript/components/hello.js, app/javascript/packs/platform.js, app/views/home/welcome.html.erb, config/environments/development.rb, config/webpack/development.js, config/webpacker.yml, docker-compose.yml, package.json, yarn.lock
Task: https://app.asana.com/0/1128645836596228/1145928107151942/f
Summary:
* Live-reload *everything* (see git commits for more detail)
* Works in docker and outside it
* Example hello.js is included to test React live reloading
* Note that the dockerfile now runs guard, instead of `rails s`
=> livereload

docker-compose/scripts/appconnect.sh, docker-compose/scripts/dbconnect.sh, docker-compose/scripts/docker_compose_run.sh, docker-compose/scripts/rebuild.sh, docker-compose/scripts/restart.sh
**Ticket(s)**:
https://app.asana.com/0/0/1147512938357231/f
**Summary**:
- Adds Docker Scripts to help with development
- Pretty much the same as in other environments
=> Adds Docker Development Scripts

package.json
This was breaking the heroku pipeline deploy. I deployed manually from this branch and verified this fixes the issue.
=> Move HMR back out of devDependencies

spec/controllers/contents_controller_spec.rb, spec/helpers/contents_helper_spec.rb, spec/models/content_spec.rb
Task: https://app.asana.com/0/1133543009734854/1143501603378319/f
I've spent way too long trying to get jest to work with ckeditor react components and its just not happening. This PR just fixes up some of the rails rspec tests. I'll come back to the React stuff later, I think we'll be able to test our non-ckeditor React components with Jest (which should be enough tbh) and everything else with selenium.
=> Rails tests

app/controllers/cas_controller.rb, spec/routing/cas/loginticket_spec.rb
**Ticket(s)**:
https://app.asana.com/0/1133543009734854/1150084536382593/f
**Summary**:
- Adds test for /loginTicket
- Small refactor to return a json
=> Adds Tests for CAS LoginTicket

Gemfile, Gemfile.lock, config/initializers/honeycomb.rb, config/secrets.yml
**Ticket(s)**:
https://app.asana.com/0/1133543009734854/1153847903754889/f
**Summary**:
- Adds Honeycomb
=> Adds Honeycomb

app.json, app/assets/stylesheets/application.scss, app/assets/stylesheets/bz_newui.css, app/javascript/ckeditor/blockquotecontentediting.js, app/javascript/ckeditor/checklistquestionediting.js, app/javascript/ckeditor/contentcommonediting.js, app/javascript/ckeditor/contentpartpreviewediting.js, app/javascript/ckeditor/iframecontentediting.js, app/javascript/ckeditor/insertblockquotecontentcommand.js, app/javascript/ckeditor/insertchecklistquestioncommand.js, app/javascript/ckeditor/insertiframecontentcommand.js, app/javascript/ckeditor/insertmatchingquestioncommand.js, app/javascript/ckeditor/insertmatchingtablerowcommand.js, app/javascript/ckeditor/insertradiocommand.js, app/javascript/ckeditor/insertradioquestioncommand.js, app/javascript/ckeditor/inserttablecontentcommand.js, app/javascript/ckeditor/matchingquestionediting.js, app/javascript/ckeditor/radioquestionediting.js, app/javascript/ckeditor/sectionediting.js, app/javascript/ckeditor/tablecontentediting.js, app/javascript/components/ContentEditor.js, app/javascript/components/ContentPartPreview.js, package.json, spec/capybara_helper.rb, spec/feature/course_contents/smoke_spec.rb, spec/integration/course_contents/smoke_spec.rb, spec/support/vcr.rb, yarn.lock
This is a bunch of stuff I did before break, that's hard to split apart now. Basic summary of what's included:
* Some refactoring/bugfixes
* New components (radio, iframe, blockquote, matching game, table)
* Heroku CI config fixes
* Basic passing tests for CKEditor stuff
* VCR mods to work with chromedriver/heroku
* Improved placeholders in editable elements
* A bunch of messing around with retained data stuff that i'll throw away later
* Copy of bz_newui.css with Sarah's mods for our new HTML
=> Editor components chunk 2

docker-compose/scripts/console.sh
I have aliases for these so I can just type `devc` in any of the
Braven repos and connect to the rails console for that project.
=> Add a convenience script to connect to the Docker rails console.

app/views/home/welcome.html.erb
=> Revert "Test commit to see if review apps work."

Procfile, app.json
Also, make db:migrate automatically run during releases.
=> Think I finally fixed Review Apps database population

app/models/organization.rb, db/migrate/20200211142232_add_organization.rb, db/schema.rb, spec/factories/organizations.rb, spec/models/organization_spec.rb
Whipped up an Organization model. Added uniqueness constraint for name. Also included some RSpec fun to test callbacks.
Test Plan: `bundle exec rspec spec/models/organization_spec.rb` and `bundle exec rspec spec/models`
=> model for Organization and associated tests

app/assets/stylesheets/course_contents.scss, app/assets/stylesheets/style.css, app/controllers/course_contents_controller.rb, app/javascript/components/ContentEditor.js, app/javascript/components/Sidebar.js, app/javascript/packs/sidebar.js, app/views/course_contents/_form.html.erb, package.json, yarn.lock
Adds a super basic left sidebar, with a wonky button and a list of created pages.
Task: https://app.asana.com/0/1142638035116665/1155859225081656/f
Screenshots:
=> Add left nav sidebar

lib/canvas_api.rb, spec/lib/canvas_api_spec.rb
Task: https://app.asana.com/0/1142638035116665/1155859225081693/f
See also https://github.com/beyond-z/canvas-lms/pull/569
=> Set new HTML flag before publishing

config/environments/production.rb
If the FORCE_SSL env var is there, it will do it.
=> Add config option to force traffic over SSL.

app/controllers/course_content_histories_controller.rb, app/controllers/course_contents_controller.rb, app/models/course_content_history.rb, app/views/course_content_histories/index.html.erb, db/migrate/20200319164632_add_user_to_course_content_histories.rb, db/schema.rb, spec/factories/course_content_histories.rb, spec/views/course_content_histories/index.html.erb_spec.rb, spec/views/course_content_histories/show.html.erb_spec.rb
Summary: Track who publishes content and display in the version index table.
* Add user reference to CourseContentHistory
* Display user email in versions index view
Task: https://app.asana.com/0/1142638035116665/1166448997769282/f
=> Track user who publishes versions

app/javascript/ckeditor/contentcommonediting.js
Task: https://app.asana.com/0/1142638035116665/1159439906066361/f
=> Allow editing answer titles

README.md
Another README update, this time with Git's autocrlf configuration.
=> Update README with Git autocrfl troubleshooting

app/javascript/ckeditor/checklistquestionediting.js, app/javascript/ckeditor/insertcheckboxcommand.js, app/javascript/ckeditor/insertradiocommand.js, app/javascript/ckeditor/radioquestionediting.js, app/javascript/ckeditor/utils.js
Don't know why this works. :/
I wish I could figure out what's going on here, but this still seems to be better than what we have now. At least it doesn't crash the whole editor. At this point I'm resigned to pushing it out and iterating as needed.
Task: https://app.asana.com/0/1142638035116665/1169461014498429/f
=> Improve checkboxDiv insertion/deletion

app/javascript/ckeditor/checklistquestionediting.js, app/javascript/ckeditor/moduleblockediting.js, app/javascript/ckeditor/radioquestionediting.js
Task: https://app.asana.com/0/1142638035116665/1170345004034689/f
Upstream issue with more information: https://github.com/ckeditor/ckeditor5/issues/6601
=> Fix module-block widget handling

app/javascript/ckeditor/iframecontentediting.js, app/javascript/ckeditor/insertiframecontentcommand.js
Task: https://app.asana.com/0/1170776727341290/1171073105499761/f
=> Fix iframe handling

app/javascript/components/ContentEditor.js
**Blame**: https://github.com/bebraven/platform/commit/b93fb9a8b36d190b257318daa8176996d7f0880a#diff-92838aff2423c239e8050b1d702f1a39R771
I wrote that line to naively fix the `Save` issue, but didn't test with the massive module data. Now I know `editor.getData()` is an expensive call. 
**Clean up**: 
Assuming this fixes the issue and doesn't regress anything, I'd like to try and clean this up a bit, starting with the `document.forms[0].submit()`. I tried this: https://pastebin.com/JTefjiqC but got a 404 error I couldn't figure out.
**Test**:
- Same as [#152](https://github.com/bebraven/platform/pull/152), with some additions
- Always use this input to test: https://stagingplatform.bebraven.org/course_contents/1/edit
- Check that editing in "Design" and clicking "Save" works
- Test that …
=> Fix performance regression

app/javascript/ckeditor/videocontentediting.js
Task: https://app.asana.com/0/1170776727341290/1170858835999045/f
Needed for module 5, which has videos in questions and in the root.
=> Allow video in question, root

app/assets/stylesheets/course_contents.scss, app/javascript/ckeditor/customelementattributepreservation.js
Summary: Some CSS changes and attribute-preservation fixes to unblock module 6.
Task: https://app.asana.com/0/1170776727341290/1171615827058130/f
=> Fix module 6 blockers

app/javascript/ckeditor/contentcommonediting.js, app/javascript/ckeditor/videocontentediting.js
Task: https://app.asana.com/0/1170776727341290/1171831755510633/f
=> Fix videos in questions

app/javascript/ckeditor/moduleblockediting.js
**Task**: https://app.asana.com/0/1168520191527013/1170510474174757
**Test**
- Create two empty sections
- Add a question to one section, fill in some fields
- Select (blue perimeter), Ctrl+C to copy
- Click into other section, Ctrl+P to paste
- Also used `Module 1` to test copy-paste on large data sets, the performance and behavior are fine. 
**Details**
The key things to note in our implementation:
- All of the data we need is in `data.getData('text/html')`. The default behavior we get from CKEditor is pasting in what is returned by `data.getData('text/plain')`. 
- We need to call `evt.stop()` to prevent other input transformations from running, or else we end up pasting in the same old, messed up plain text.
- We have to let model conversion know we're in the context of `section`, so …
=> Copy-paste for checklist question

app/javascript/ckeditor/contentcommonediting.js, app/javascript/ckeditor/insertfileuploadquestioncommand.js, app/javascript/components/ContentEditor.js
And disable fileUpload inputs in the edit view.
Task: https://app.asana.com/0/1170776727341290/1172267779433977/f
=> Add fileUpload question button

app/javascript/ckeditor/contentcommonediting.js
Task: https://app.asana.com/0/1142638035116665/1169209719391233/f
See code comment for details.
=> Support live-update for correctness and placeholder

app/assets/stylesheets/course_contents.scss, app/javascript/ckeditor/contentcommonediting.js, app/javascript/ckeditor/iframecontentediting.js, app/javascript/ckeditor/insertiframecontentcommand.js, app/javascript/ckeditor/insertmatchingquestioncommand.js, app/javascript/ckeditor/insertmatchingtablerowcommand.js, app/javascript/ckeditor/matchingquestionediting.js, app/javascript/ckeditor/ratethismodulequestionediting.js, app/javascript/ckeditor/videocontentediting.js, app/javascript/components/ContentEditor.js
This is a big one, but hopefully it sorts some things out. 
Task: https://app.asana.com/0/1170776727341290/1171026326095789/f
(Related task: https://app.asana.com/0/1142638035116665/1155859225081705/f)
=> Audit and fix selection/limit issues

Dockerfile, README.md, app/controllers/application_controller.rb, app/views/home/welcome.html.erb, docker-compose.yml, docker-compose/scripts/docker_compose_run.sh
1. Run the docker container using a script so we can check some things and give messages.
2. Add a check for the SALESFORCE related ENV vars and let them know what to do.
3. Make adding new gems easier.
4. Drop some more convenience links on our homepage.
Test Plan:
1. Do a container rebuild and make sure it works.
2. Add a gem to Gemfile and notice how guard re-runs bundle install and makes the updated Gemfile.lock available outside the container. They you can just check it in instead of having to rebuild.
3. Remove one of the SALESFORCE env vars and notice the message you get in the logs telling you what to do.
4. Go to the home page and try out the new Sync TO LMS and Portal links.
=> A little dev env cleanup.

app/controllers/users/passwords_controller.rb, app/helpers/cas_helper.rb, app/models/user.rb, app/views/cas/login.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, config/initializers/devise.rb, config/routes.rb
- Go to http://platformweb:3020/users/password/new
- Enter a valid email address.
- Click on the link in the email. E.g. http://platformweb:3020/users/password/edit?reset_password_token=-M8AhGf-rdNhtkC4Mxvr
- Enter a new password and it will log you in.
- Make sure the the login works by starting a new browser session and loggin in with the new password.
This is mostly devise boilerplate. The only thing to review is `config/initializers/devise.rb` for now. I'll be doing future iterations of the other stuff to actually make it look and flow nice.
=> Implement forgot password.

docker-compose.yml
I don't know if this will have side effects, but I did some basic tests
and it seems to speed things up A LOT (after the first build) and JS changes
did get reloaded / reflected
=> Make webpack fast on restarts.

app/controllers/file_upload_controller.rb, app/javascript/components/ContentEditor.js, config/routes.rb, lib/canvas_api.rb, spec/controllers/file_upload_controller_spec.rb, spec/lib/canvas_api_spec.rb
Task: https://app.asana.com/0/1170776727341290/1172626862010553/f
I'm not sure how to rspec the controller for this, @sadleb any suggestions?
=> Implement image upload

.env.example, app/controllers/users/confirmations_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/passwords/check_email.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/registrations/show.html.erb, app/views/devise/shared/_links.html.erb, config/routes.rb
https://app.asana.com/0/1170770467635599/1173702089144330
This wraps up the basic functionality of forgot password as a follow-up to https://github.com/bebraven/platform/pull/181 
1. Gives you instructions about what to do after you submit the forgot password form.
2. Logs you in once you change your password.
3. Makes "re-send confirmation" work
4. Cleans up the forgot password, resend confirmation, sign-up, and log-in links on the various forms.
1. Sign-up a new user.
2. Click button to re-send confirmation link.
3. Click the confirmation link.
4. Log-in
5. Start a new browser session and click forgot password on the log-in page.
6. Enter your email and submit.
7. Use the link to change your password and get auto-logged in.
=> Forgot password flow and better registration / confirmation flow as well.

app/views/devise/passwords/edit.html.erb
Test Plan:
1. On the sign-in page click "Forgot password"
2. Click the link in the email
3. The "create a new password" page should look like the other signin/signup/password pages.
=> Apply new account layout to the edit password form.

app/controllers/cas_controller.rb
This controller was a copy/paste of bits and pieces of the old Join
server code along with the rubycas SSO server. It's a mess. I just
opened up a PR to run a tiny bit of this logic when confirming your
new account here: https://github.com/bebraven/platform/pull/215
and learned something about the rubycas-server-core gem's code.
This takes a small pass at starting to clean this controller up by only
including the top-level Tickets utility class and using that to do all the
ticket generation and validation.
Note: the proxy ticket stuff isn't implemented in that Tickets module
so I hacked that logic to follow the same patterns with the goal of moving
that code to the gem at some point.
Test Plan:
- Login/logout of both platform and portal still work.
- bundle exec rspec spec/controllers/cas
=> Cleanup the CAS controller a bit.

app/controllers/users/confirmations_controller.rb
It's in application_controller now.
=> Forgot to remove a method I moved.

Gemfile, Gemfile.lock, Guardfile
I think this was broken by #212, and we don't need it anyway, so let's just remove it.
=> Remove guard-bundler

Gemfile.lock
I guess bundle update is required and not just bundle install.
=> Update the rowan_bot gem for real this time.

Gemfile.lock
=> Update Rowan Bot

Gemfile.lock
=> Update Rowan Bot Gem

app/models/program.rb, lib/salesforce_api.rb, lib/sync_to_lms.rb
This updates the user creation in LMS to add a different docusign ID for LCs. It also fix the filter issue when getting users course enrolments from LMS.
=> Update sync to lms flow

README.md, docker-compose/scripts/dbrefresh.sh
Also, sneak in a fix for the dbrefresh script. Sorry. Bad form to have this in the PR too.
=> Update README with info about setting up an LTI dev env.

.env.example
Task: https://app.asana.com/0/1174274412967132/1181167037101953/f
=> Add comment to .env.example

app/controllers/salesforce_controller.rb, app/jobs/application_job.rb, app/jobs/salesforce_program_to_lms_sync_job.rb, app/mailers/application_mailer.rb, app/mailers/salesforce_to_lms_sync_mailer.rb, app/views/salesforce/_form.html.erb, app/views/salesforce_to_lms_sync_mailer/failure_email.html.erb, app/views/salesforce_to_lms_sync_mailer/success_email.html.erb, lib/canvas_api.rb, lib/sync_to_lms.rb, spec/jobs/salesforce_program_to_lms_sync_job_spec.rb, spec/lib/canvas_api_spec.rb, spec/mailers/previews/salesforce_to_lms_sync_mailer_preview.rb, spec/mailers/salesforce_to_lms_sync_mailer_spec.rb
This PR implements the following:
- Use a background job to run the sync.
- Send emails on success or failures.
- Reactivate SIS instead of throwing error.
https://app.asana.com/0/1172786304330247/1172130267952718
=> Update sync to lms

app/mailers/application_mailer.rb, config/secrets.yml
This changes the default from email from `noreply@braven.org` to `noreply@bebraven.org`
This was causing an error about `@braven.org` not verified
=> Update default from email

Gemfile, Gemfile.lock
See: https://github.com/pschinis/rails_same_site_cookie
Requires a rebuild. 
Note: 
* this handles SameSite=none and Secure flags. 
* you may experience infinite redirects when accessing platformweb over http. be sure to use HTTPS.
=> Add same-site/secure cookie

Gemfile, Gemfile.lock, app/models/lesson_content.rb, config/application.rb, config/routes.rb, lib/lesson_content_publisher.rb, lib/lti_lesson_contents_proxy.rb, spec/lib/lesson_content_publisher_spec.rb, spec/lib/lti_lesson_contents_proxy_spec.rb, spec/rails_helper.rb, spec/support/http_streaming_response_patch.rb
Please never look at this set of commits and merges. I accidentally hit "merge" instead of "squash and merge" and blindly hit "revert" to try and ... well look at the mess I made. Here is what is in this PR: https://github.com/bebraven/platform/pull/293
This reverts commit 52329a978c7251c8c5276c3cfcab83428dd6bb6b.
=> Revert "Revert "Adds a reverse proxy to the AWS S3 hosted files for the LTI lessons

app/javascript/components/hello.js
Just a comment for my first pull request
https://app.asana.com/0/1186096774011274/1190803167140319
=> Added a variable hello

Gemfile, Gemfile.lock, app/controllers/admin/join_controller.rb, app/jobs/sync_salesforce_program_to_join_job.rb, app/mailers/sync_salesforce_to_join_mailer.rb, app/services/sync_join_users_for_program.rb, app/views/admin/join/_sync_to_join_form.html.erb, app/views/admin/join/init_sync_to_join.html.erb, app/views/home/welcome.html.erb, app/views/sync_salesforce_to_join_mailer/failure_email.html.erb, app/views/sync_salesforce_to_join_mailer/success_email.html.erb, config/routes.rb, spec/mailers/previews/salesforce_to_join_sync_mailer_preview.rb, spec/mailers/sync_salesforce_to_join_mailer_spec.rb
Allow for running sync to join
We need to have all participants to have join users
=> Add sync to join

app/javascript/ckeditor/checklistquestionediting.js, app/javascript/ckeditor/contentcommonediting.js, app/javascript/ckeditor/insertchecklistothercommand.js, app/javascript/ckeditor/sliderquestionediting.js
Worked on sliderquestionediting.js file
Added aria-live="polite" to the feedback section 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
=> fixed checklist question

app/views/devise/mailer/confirmation_instructions.html.erb, app/views/layouts/admin.html.erb, app/views/layouts/application.html.erb
I set **lang="en"** for each layout
- [X ] Bug fix (non-breaking change which fixes an issue)
=> fixed html language attribute

app/services/setup_portal_account.rb, lib/salesforce_api.rb
This allows for portal ID for booster to be updated differently on SF.
This was required from the data team
https://app.asana.com/0/1178906757852153/1195445524446161
=> Update portal ID for booster differently

app/services/account_creator.rb, app/services/setup_portal_account.rb, app/services/sync_portal_enrollments_for_program.rb, lib/salesforce_api.rb, spec/services/setup_portal_account_spec.rb
This updates the way sync to lms works for NLU program.
NLU has a slightly different requirement for how fellows join our system. The fellow need to have their accounts created when running a sync to lms.
https://app.asana.com/0/1185361437008970/1199201476879535
=> Update sync for nlu
